using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TinderSuitev3.Helpers
{
    public static class Lists
    {
        public static Dictionary<string, int> WeightedWords = new Dictionary<string, int>()
        {
            { "snapchat", 2 },
            { "snap", 8 },
            { "insta", 6 },
            { "ig:", 6 },
            { " ig ", 6 },
            { "snvpchvt", 100 },
            { "snap chat", 5 },
            { "snap-", 15 },
            { "snap:", 15 },
            { "snvp-", 100 },
            { "sпap", 100 },
            { "sпapchat", 100 },
            { "make content", 20 },
            { "some content", 20 },
            { "a good time", 20 },
            { "😘", 5 },
            { "💞", 5 },


        };

        public static string[] Races = new string[]
        {
            "Caucasian",
            "Asian",
            "African American",
            "Latin(x)",
            "Indian",
        };

        public static string[] StarSigns =
        {
            "Aries",
            "Taurus",
            "Gemini",
            "Cancer",
            "Leo",
            "Virgo",
            "Libra",
            "Scorpio",
            "Sagittarius",
            "Aquarius",
            "Pisces",
            "Capricorn"
        };

        public static string[] Hobbies =
        {
            "Harry Potter",
            "90s Kid",
            "SoundCloud",
            "Spa",
            "Self Care",
            "Heavy Metal",
            "House Parties",
            "Gin Tonic",
            "Gymnastics",
            "Hot Yoga",
            "Meditation",
            "Spotify",
            "Sushi",
            "Hockey",
            "Basketball",
            "Slam Poetry",
            "Home Workout",
            "Theater",
            "Cafe Hopping",
            "Aquarium",
            "Sneakers",
            "Instagram",
            "Hot Springs",
            "Walking",
            "Running",
            "Travel",
            "Language Exchange",
            "Movies",
            "Guitarists",
            "Social Development",
            "Gym",
            "Social Media",
            "Hip Hop",
            "Skincare",
            "J-Pop",
            "Shisha",
            "Cricket",
            "Freelance",
            "Skateboarding",
            "Gospel",
            "K-Pop",
            "Potterhead",
            "Trying New Things",
            "Photography",
            "Bollywood",
            "Reading",
            "Singing",
            "Sports",
            "Poetry",
            "Stand up Comedy",
            "Coffee",
            "Karaoke",
            "Fortnite",
            "Free Diving",
            "Self Development",
            "Mental Health Awareness",
            "Foodie Tour",
            "Voter Rights",
            "Jui-jitsu",
            "Climate Change",
            "Exhibition",
            "Walking My Dog",
            "LGBTQ+ Rights",
            "Feminism",
            "VR Room",
            "Escape Cafe",
            "Shopping",
            "Brunch",
            "Investment",
            "Second-hand apparel",
            "Jetski",
            "Reggaeton",
            "Black Lives Matter",
            "Jogging",
            "Road Trips",
            "Vintage Fashion",
            "Voguing",
            "Couchsurfing",
            "Happy Hour",
            "Incluvisity",
            "Country Music",
            "Football",
            "Inline Skate",
            "Investing",
            "Tennis",
            "Ice Cream",
            "Ice Skating",
            "Human Rights",
            "Expositions",
            "Skiing",
            "Pig Roast",
            "Snowboarding",
            "Canoeing",
            "West End Musicals",
            "Pilates",
            "Pentathlon",
            "Broadway",
            "PlayStation",
            "Cheerleading",
            "Choir",
            "Pole Dancing",
            "Five-a-side Football",
            "Car Racing",
            "Pinterest",
            "Festivals",
            "Pub Quiz",
            "Catan",
            "Cosplay",
            "Motor Sports",
            "Coffee Stall",
            "Content Creation",
            "E-Sports",
        };
    }
}
